export const quizes = {
    quizTitle: "TPRS Story",
    quizSynopsis: "",
    statements: [
      {
        statement: "هناك ولد",
        questions: [
          {
            question: "هل هناك ولد؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "تم تأكيد وجود ولد في الجملة",
            point: "20",
          },
          {
            question: "هل هناك ولد أو بنت؟",
            answers: ["ولد", "بنت"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى ولد",
            point: "20",
          },
          {
            question: "هل هناك بنت؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير إلى وجود ولد، وليس بنت",
            point: "20",
          },
          {
            question: "من يوجد هناك؟",
            answers: ["ولد", "بنت"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد وجود ولد",
            point: "20",
          },
        ],
      },
      {
        statement: "الولد هو أبو",
        questions: [
          {
            question: "هل الولد هو أبو؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أن الولد هو أبو",
            point: "20",
          },
          {
            question: "هل الولد أبو أو عمر؟",
            answers: ["أبو", "عمر"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أن الولد هو أبو",
            point: "20",
          },
          {
            question: "هل الولد هو عمر؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أن الولد هو أبو وليس عمر",
            point: "20",
          },
          {
            question: "من هو الولد؟",
            answers: ["أبو", "عمر"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أن الولد هو أبو",
            point: "20",
          },
        ],
      },
      {
        statement: "أنت ولد",
        questions: [
          {
            question: "هل أنت ولد؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنك ولد",
            point: "20",
          },
          {
            question: "هل أنت ولد أو بنت؟",
            answers: ["ولد", "بنت"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنك ولد",
            point: "20",
          },
          {
            question: "هل أنت بنت؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنك ولد وليس بنت",
            point: "20",
          },
          {
            question: "ماذا أنت؟",
            answers: ["ولد", "بنت"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنك ولد",
            point: "20",
          },
        ],
      },
      {
        statement: "أنت أبو",
        questions: [
          {
            question: "هل أنت أبو؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنك أبو",
            point: "20",
          },
          {
            question: "هل أنت أبو أو محمد؟",
            answers: ["أبو", "محمد"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنك أبو",
            point: "20",
          },
          {
            question: "هل أنت محمد؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنك أبو وليس محمد",
            point: "20",
          },
          {
            question: "من أنت؟",
            answers: ["أبو", "محمد"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنك أبو",
            point: "20",
          },
        ],
      },
      {
        statement: "أنت لست كبابًا",
        questions: [
          {
            question: "هل أنت كباب؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنك لست كبابًا",
            point: "20",
          },
          {
            question: "هل أنت كباب أو ولد؟",
            answers: ["كباب", "ولد"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنك ولد وليس كباب",
            point: "20",
          },
          {
            question: "هل أنت ولد؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنك ولد",
            point: "20",
          },
          {
            question: "من أنت؟",
            answers: ["ولد", "كباب"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنك ولد",
            point: "20",
          },
        ],
      },
      {
        statement: "هناك كباب",
        questions: [
          {
            question: "هل هناك كباب؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد وجود كباب",
            point: "20",
          },
          {
            question: "هل هناك كباب أو شواء؟",
            answers: ["كباب", "شواء"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى وجود كباب",
            point: "20",
          },
          {
            question: "هل هناك شواء؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير إلى وجود كباب وليس شواء",
            point: "20",
          },
          {
            question: "ما الموجود؟",
            answers: ["كباب", "شواء"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد وجود كباب",
            point: "20",
          },
        ],
      },
      {
        statement: "أنا كباب",
        questions: [
          {
            question: "هل أنا كباب؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنني كباب",
            point: "20",
          },
          {
            question: "هل أنا كباب أو خبز؟",
            answers: ["كباب", "خبز"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنني كباب",
            point: "20",
          },
          {
            question: "هل أنا خبز؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنني كباب وليس خبز",
            point: "20",
          },
          {
            question: "من أنا؟",
            answers: ["كباب", "خبز"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنني كباب",
            point: "20",
          },
        ],
      },
      {
        statement: "أنا الكباب",
        questions: [
          {
            question: "هل أنا الكباب؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنني الكباب",
            point: "20",
          },
          {
            question: "هل أنا الكباب أو التبولة؟",
            answers: ["كباب", "تبولة"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنني الكباب",
            point: "20",
          },
          {
            question: "هل أنا التبولة؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنني الكباب وليس التبولة",
            point: "20",
          },
          {
            question: "من أنا؟",
            answers: ["كباب", "تبولة"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنني الكباب",
            point: "20",
          },
        ],
      },
      {
        statement: "أنا كمال",
        questions: [
          {
            question: "هل أنا كمال؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنني كمال",
            point: "20",
          },
          {
            question: "هل أنا كمال أو كريم؟",
            answers: ["كمال", "كريم"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنني كمال",
            point: "20",
          },
          {
            question: "هل أنا كريم؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنني كمال وليس كريم",
            point: "20",
          },
          {
            question: "من أنا؟",
            answers: ["كمال", "كريم"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنني كمال",
            point: "20",
          },
        ],
      },
      {
        statement: "أنا كمال الكباب",
        questions: [
          {
            question: "هل أنا كمال الكباب؟",
            answers: ["نعم", "لا"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنني كمال الكباب",
            point: "20",
          },
          {
            question: "هل أنا كمال الكباب أو كريم الشاورما؟",
            answers: ["كمال الكباب", "كريم الشاورما"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنني كمال الكباب",
            point: "20",
          },
          {
            question: "هل أنا كريم الشاورما؟",
            answers: ["نعم", "لا"],
            correctAnswer: "2",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يشير بوضوح إلى أنني كمال الكباب وليس كريم الشاورما",
            point: "20",
          },
          {
            question: "من أنا؟",
            answers: ["كمال الكباب", "كريم الشاورما"],
            correctAnswer: "1",
            messageForCorrectAnswer: "إجابة صحيحة. عمل جيد",
            messageForIncorrectAnswer: "إجابة غير صحيحة. حاول مرة أخرى",
            explanation: "البيان يؤكد أنني كمال الكباب",
            point: "20",
          },
        ],
      },
    ],
  };
  